### ISSUE TITLE
wordpress issue

### ISSUE THREAD

**Issue by imSunnyk** [kaushikjadhav01/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis#3]
After downloading WordPress how to set it up....

**Comment by kaushikjadhav01** [comment]
Install Wordpress with standard settings. Once done, install  All In One WP Migration Plugin on Wordpress. Then, download my .wpress file from link in README of my repo. Go to plugin and import the file.

I had already mentioned these steps in installation instructions of README of my repo. Please read it carefully.
