### ISSUE TITLE
Issues with wordpress links

### ISSUE THREAD

**Issue by octoma** [kaushikjadhav01/Stock-Market-Prediction-Web-App-using-Machine-Learning-And-Sentiment-Analysis#8]
Hello. I'm excited to use the program, but I can't get the links in wordpress to work. I've installed it on xampp/Linux mint 19. Here is what I've tried so far.

Updated WP permalinks
Updated . Htaccess file (tried multiple variations)

Any ideas?
Thanks

**Comment by kapilraj2436** [comment]
were you able to download wordpress project from the link?
